
name: PR for release branch
on:
  pull_request:
    types:
      [ closed ]
jobs:
  release_pull_request:
    if: ${{github.event.pull_request.merged}} == 'true' && ${{github.event.pull_request.base.ref}} == 'true' && contains(github.event.pull_request.label.*.name, 'bug')
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: get_latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - id: get_short_version
      run: |
        major_minor=$(echo ${{steps.get_latest_tag.outputs.tag}} | cut -d '.' -f 1,2)
        echo "::set-output name=major_minor::$major_minor"
    - run: echo "${{steps.get_short_version.outputs.id}}"
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: ${{steps.get_short_version.outputs.major_minor}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: false
