on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Previous tag'
        id: get_latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.get_latest_tag.outputs.tag }}
