name: versionbump
on:
  push:
    branches:
      - lts

jobs:
  build:
    if: github.event.pull_request.merged && ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        run: |
          git config --global user.name 'ProjectBot'
          git config --global user.email 'bot@users.noreply.github.com'
          CURRENTVERSION=$(sed -nr '0,/^{% set version = "\([^"]*\)" %}/s//\1/p' ${{github.workspace}}/recipe/meta.yaml)
          echo $CURRENTVERSION

